#! /bin/sh

#autostart apps
pgrep -x sxhkd > /dev/null || sxhkd &

#pywall stuff
wal -i `shuf -n1 -e ~/Pictures/wall/*` -o "~/.config/scripts/update_firefox.sh"
# source the colors.
. "${HOME}/.cache/wal/colors.sh"

# compositor
picom --experimental-backends &

# borders
## wal colors
## Set the border colors. Taken from doc
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color1"

bspc config border_width 5
bspc config borderless_monocle true

# workspaces 
bspc monitor -d 1 2 3 4 5 6 7 8 9 0

bspc config focus_follows_pointer true

bspc config top_padding 20

# remove border for this
bspc rule -a Dunst border=off

#gaps 
bspc config gapless_monocle false
bspc config window_gap 10
bspc config split_ratio 0.50

# rules
bspc rule -a discord desktop=^9
bspc rule -a firefox desktop=^2
bspc rule -a Chromium desktop=^3
bspc rule -a 'Steam' desktop=^8 state=fullscreen 
bspc rule -a "Wine" state=floating
bspc rule -a "flameshot" state=floating
bspc rule -a "guiscrcpy" state=floating
bspc rule -a "scrcpy" state=floating
bspc rule -a "peek" state=floating
bspc rule -a "VirtualBox Machine" state=floating

# polybar 
~/.config/polybar/launch.sh &

#nofifications
killall dunst 
dunst &

# Battery signal
killall batsignal
batsignal -b -w 35 -c 20 -d 10 -f 90 -W "Charge plox uwu" -C "I'm dying, charge me plox" -D "Charge this damn laptop mf" -F "Pull out!!! I don't want to have a degenerates kid" -a "System" -I "/home/panda/Pictures/icons/arch_linux_icon.jpg"  &

#redshift
redshift -x && redshift -O 3500K 

#mpd 
killall mpd
mpd ~/.mpd/mpd.conf

# some applets
killall flameshot blueman-applet nm-applet copyq
flameshot &
blueman-applet &
nm-applet &
copyq &

# This is gonna pause the other commands so it is at last
change_lock.sh &

